export const theme = {
  colors: {
    primary: '#4F46E5',
    primaryDark: '#4338CA',
    primaryLight: '#EEF2FF',
    accent: '#6366F1',
    background: '#F8FAFC',
    surface: '#FFFFFF',
    surfaceSecondary: '#F1F5F9',
    textPrimary: '#0F172A',
    textSecondary: '#64748B',
    textMuted: '#94A3B8',
    textWhite: '#FFFFFF',
    border: '#E2E8F0',
    borderFocused: '#4F46E5',
    borderError: '#EF4444',
    error: '#EF4444',
    errorLight: '#FEE2E2',
    errorText: '#B91C1C',
    success: '#10B981',
    successLight: '#D1FAE5',
    successText: '#047857',
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 12,
    lg: 16,
    xl: 20,
    xxl: 24,
    xxxl: 32,
    huge: 48,
  },
  borderRadius: {
    xs: 4,
    sm: 8,
    md: 12,
    lg: 16,
    xl: 24,
    round: 9999,
  },
  typography: {
    caption: {
      fontSize: 12,
      lineHeight: 16,
    },
    bodySm: {
      fontSize: 14,
      lineHeight: 20,
    },
    body: {
      fontSize: 16,
      lineHeight: 24,
    },
    subtitle: {
      fontSize: 16,
      lineHeight: 24,
      fontWeight: '600',
    },
    titleSm: {
      fontSize: 18,
      lineHeight: 24,
      fontWeight: '600',
    },
    title: {
      fontSize: 22,
      lineHeight: 28,
      fontWeight: '700',
    },
    heading: {
      fontSize: 28,
      lineHeight: 34,
      fontWeight: '800',
    },
  },
  shadows: {
    subtle: {
      shadowColor: '#0F172A',
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.05,
      shadowRadius: 2,
      elevation: 2,
    },
    card: {
      shadowColor: '#0F172A',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.08,
      shadowRadius: 8,
      elevation: 4,
    },
    elevated: {
      shadowColor: '#4F46E5',
      shadowOffset: { width: 0, height: 6 },
      shadowOpacity: 0.15,
      shadowRadius: 12,
      elevation: 6,
    },
  },
};

